### ISSUE TITLE
Mistake in the proof on pigeonhole principle page

### ISSUE THREAD

**Issue by jhrcek** [mrpandey/d3graphTheory#12]
Thanks for creating this, I like this interactive course!

There is a mistake in the proof at https://mrpandey.github.io/d3graphTheory/unit.html?pigeonhole

The argument goes like:
1. if graph has vertex with degree 0 then ..
2. if graph has vertex with degree n-1 then..

But the argument says nothing about graphs that don't have one of the vertices with such degrees.

To be correct, it should probably go something like this:
1. if graph has vertex with degree 0 then we're choosing from degrees 0 .. n-2
2. if graph doesn't have vertex with degree 0 then we're choosing from degrees 1..n-1

**Comment by mrpandey** [comment]
@jhrcek thanks for pointing out. I have corrected it.
