### ISSUE TITLE
repeated start node not detected

### ISSUE THREAD

**Issue by sarming** [mrpandey/d3graphTheory#2]
In the chapter open-vs-closed, when the start node is visited multiple times the walk is wrongly shown to be a path/cycle.

**Comment by mrpandey** [comment]
Hello! Thanks for your feedback.
I am not able to reproduce the situation. Are we both following the same definitions for cycle? In the definition I am following, the start and end vertices can coincide (or repeat) in a cycle. If it's still not okay, please let me know how you produced the situation. Thanks again.

**Comment by sarming** [comment]
I would not consider 1,2,1,3,1 a cycle.

**Comment by mrpandey** [comment]
You're correct. That isn't a cycle. I did some fixing. See if it's okay now.

**Comment by sarming** [comment]
Looks good to me.
I really enjoyed playing around :) Great project!
