### ISSUE TITLE
💡show symbols inline with text 

### ISSUE THREAD

**Issue by micahstubbs** [mrpandey/d3graphTheory#4]
it might be nice to show the symbols used in the graphic inline with the text.  you could think of this as a legend, but in context, right next to the text.

I made a quick design of what [this page](https://mrpandey.github.io/d3graphTheory/unit.html) could look like, with the symbols inline:

<img width="1757" alt="vertex-shape-design" src="https://user-images.githubusercontent.com/2119400/37667481-59b73d0e-2c1f-11e8-9072-485992644c75.png">

**Comment by mrpandey** [comment]
That's a good idea. That will reduce the unnecessary text. I checked your changes. How did you add that edge symbol? It wasn't in the code.

**Comment by micahstubbs** [comment]
edge symbols were not on the branch until just now 😄 

here is how I draw the edge symbol:

![screen shot 2018-03-24 at 9 56 08 pm](https://user-images.githubusercontent.com/2119400/37871892-32e7927c-2fae-11e8-874d-1fc06e1969e9.png)

 draw an svg line, wrap it in a `<g>` and an `<svg>`, then wrap that in a `<span>`

`<span style: 'whitespace: nowrap'><svg width=30 height=30 xml:space='preserve' style='margin-left: 4; margin-right: 0 position:relative'><g><line x1='5' y1='25' x2='25' y2='5' stroke='#888' stroke-width='2px' stroke-linecap='round' stroke-linejoin='round'/></g></svg><\/span>`

or formatted nicely

```
<span style: 'whitespace: nowrap'>
  <svg width=30 height=30 xml:space='preserve' style='margin-left: 4; margin-right: 0 position:relative'>
    <g>
      <line x1='5' y1='25' x2='25' y2='5' stroke='#888' stroke-width='2px' stroke-linecap='round' stroke-linejoin='round'/>
    </g>
  </svg>
</span>
```

**Comment by micahstubbs** [comment]
PR here 😄 https://github.com/mrpandey/d3graphTheory/pull/6

![screen shot 2018-03-21 at 7 54 37 pm](https://user-images.githubusercontent.com/2119400/37748961-f06d8c98-2d42-11e8-8894-03ebf3452605.png)
