### ISSUE TITLE
Terminology for programming

### ISSUE THREAD

**Issue by abitrolly** [mrpandey/d3graphTheory#8]
I feel like mathematical conventions are not so useful for programming. Maybe provide some API that can be more useful for practical tasks around graphs, or at least show how this math looks like in code. For example:

* order - graph.nodes.len
* size - graph.edges.len
---
* degree - node.edges.len
* minimum degree - min([n.edges.len for n in graph.nodes])
* maximum degree - max([n.edges.len for n in graph.nodes])
---
* degree sequence - sorted([n.edges.len for n in graph.nodes], reverse=True)
* sum of vertices degree is twice the size of graph - graph.edges.len*2 == sum([n.edges.len for n in graph.nodes])
---

**Comment by mrpandey** [comment]
So if I get you right, you are suggesting to make changes in code so as to group `nodes` and `links` in single object `graph` and make changes to other terms similarly? This really seems to be a good idea and makes code more readable. I will do it after my university exams are over.
