### ISSUE TITLE
Consistent terms for structured knowledge

### ISSUE THREAD

**Issue by AhliLi** [mrpandey/d3graphTheory#9]
Though "Dot"+"Edge" and RAND Node-Link are usable, it is better to describe graph systems as "Concepts related to Concepts by Concepts" where all structured knowledge and all structured associative knowledge is abstracted (as is type "class" representations of the knowledge)

**Comment by mrpandey** [comment]
Sorry, but I don't quite get you. What do you mean by "Concepts related to Concepts by Concepts"?
